import React from 'react';
import { Route, ActionType } from '../types';

/* ------------------------------------------------------------------ */
/* Nginx snippet builder (route drawer preview)                        */
/* ------------------------------------------------------------------ */

export function buildNginxSnippet(route: Route): string {
  const domain = route.isCatchAll ? '_' : route.domain;
  const isSsl = route.protocol === 'HTTPS';
  const listenPort = route.portNum ?? (isSsl ? 443 : route.portRaw ? parseInt(String(route.portRaw), 10) || 80 : 80);
  const listenLine = isSsl ? `listen ${listenPort} ssl;` : `listen ${listenPort};`;

  const lines: string[] = [];
  lines.push(`# Generated by PortWatch — ${route.domain}${route.path}`);
  lines.push('server {');
  lines.push(`    ${listenLine}`);
  lines.push(`    server_name ${domain};`);
  lines.push('');

  const location = route.path && route.path !== '/' ? route.path : '/';
  const action: ActionType = route.action;

  if (action === 'Proxy') {
    lines.push(`    location ${location} {`);
    lines.push(`        proxy_pass ${route.targetRaw || 'http://backend'};`);
    lines.push('        proxy_http_version 1.1;');
    if (route.flags?.websocket) {
      lines.push('        proxy_set_header Upgrade $http_upgrade;');
      lines.push('        proxy_set_header Connection "upgrade";');
    }
    lines.push('        proxy_set_header Host $host;');
    lines.push('        proxy_set_header X-Real-IP $remote_addr;');
    lines.push('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
    lines.push('        proxy_set_header X-Forwarded-Proto $scheme;');
    lines.push('    }');
  } else if (action === 'Static') {
    lines.push(`    root ${route.staticRoot || '/usr/share/nginx/html'};`);
    lines.push('    index index.html;');
    lines.push('');
    lines.push(`    location ${location} {`);
    lines.push('        try_files $uri $uri/ /index.html;');
    lines.push('    }');
  } else if (action === 'Redirect') {
    lines.push(`    location ${location} {`);
    lines.push(`        return ${route.redirectCode || 301} ${route.targetRaw || '$request_uri'};`);
    lines.push('    }');
  } else if (action === 'Return') {
    lines.push(`    location ${location} {`);
    lines.push(`        return ${String(route.targetRaw || '200').replace(/;+$/, '')};`);
    lines.push('    }');
  } else if (action === 'Status') {
    lines.push(`    location ${location} {`);
    lines.push('        stub_status on;');
    lines.push('        allow 127.0.0.1;');
    lines.push('        deny all;');
    lines.push('    }');
  } else {
    lines.push(`    location ${location} {`);
    lines.push(`        # ${route.targetType || 'unknown'} target: ${route.targetRaw || ''}`);
    lines.push('    }');
  }

  lines.push('}');
  return lines.join('\n');
}

/* ------------------------------------------------------------------ */
/* Nginx config parser (partition sidebar for config-file viewer)      */
/* ------------------------------------------------------------------ */

export type NginxBlockType = 'server' | 'upstream' | 'map' | 'location' | 'if' | 'http' | 'stream' | 'events' | 'other';

export interface NginxBlock {
  type: NginxBlockType;
  header: string;
  arg: string;
  startLine: number; // 1-based, line containing '{'
  endLine: number;   // 1-based, line containing '}'
  depth: number;
  children: NginxBlock[];
  rawLines: string[];
  serverNames: string[];
  listens: string[];
  label: string;
}

export interface NginxParseResult {
  blocks: NginxBlock[];   // top-level blocks
  lineCount: number;
  errors: string[];
}

function stripComment(line: string): string {
  let inS = false;
  let inD = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '\\' && (inS || inD)) { i++; continue; }
    if (c === "'" && !inD) inS = !inS;
    else if (c === '"' && !inS) inD = !inD;
    else if (c === '#' && !inS && !inD) return line.slice(0, i);
  }
  return line;
}

function firstKeyword(header: string): { kw: string; arg: string } {
  const trimmed = header.trim();
  const m = trimmed.match(/^([A-Za-z_][A-Za-z0-9_-]*)\s*([\s\S]*)$/);
  if (!m) return { kw: '', arg: trimmed };
  return { kw: m[1].toLowerCase(), arg: (m[2] || '').trim() };
}

function extractDirective(rawLines: string[], name: string): string[] {
  const out: string[] = [];
  const re = new RegExp(`(^|[\\s;{])${name}\\s+([^;]+);`, 'i');
  for (const line of rawLines) {
    const code = stripComment(line);
    const m = code.match(re);
    if (m) out.push(m[2].trim().replace(/\s+/g, ' '));
  }
  return out;
}

export function parseNginx(content: string): NginxParseResult {
  const lines = content.split('\n');
  const roots: NginxBlock[] = [];
  const stack: NginxBlock[] = [];
  const errors: string[] = [];

  const kwToType = (kw: string): NginxBlockType => {
    if (kw === 'server' || kw === 'upstream' || kw === 'map' || kw === 'location' ||
        kw === 'if' || kw === 'http' || kw === 'stream' || kw === 'events') return kw as NginxBlockType;
    return 'other';
  };

  lines.forEach((line, idx) => {
    const lineNo = idx + 1;
    const code = stripComment(line);
    let headerBuf = '';

    for (let i = 0; i < code.length; i++) {
      const c = code[i];

      // Skip ${...} interpolation braces
      if (c === '$' && code[i + 1] === '{') {
        let j = i + 2;
        while (j < code.length && code[j] !== '}') j++;
        headerBuf += code.slice(i, Math.min(j + 1, code.length));
        i = j;
        continue;
      }

      if (c === '"' || c === "'") {
        const quote = c;
        let j = i + 1;
        while (j < code.length && code[j] !== quote) {
          if (code[j] === '\\') j++;
          j++;
        }
        headerBuf += code.slice(i, Math.min(j + 1, code.length));
        i = j;
        continue;
      }

      if (c === '{') {
        const { kw, arg } = firstKeyword(headerBuf);
        const block: NginxBlock = {
          type: kwToType(kw),
          header: headerBuf.trim(),
          arg,
          startLine: lineNo,
          endLine: lineNo,
          depth: stack.length,
          children: [],
          rawLines: [line],
          serverNames: [],
          listens: [],
          label: kw || 'block'
        };
        const parent = stack[stack.length - 1];
        if (parent) parent.children.push(block);
        else roots.push(block);
        stack.push(block);
        headerBuf = '';
        continue;
      }

      if (c === '}') {
        const block = stack.pop();
        if (block) {
          block.endLine = lineNo;
          if (block.rawLines[block.rawLines.length - 1] !== line) block.rawLines.push(line);
        } else {
          errors.push(`Line ${lineNo}: unmatched '}'`);
        }
        continue;
      }

      headerBuf += c;
    }

    // Attach the raw line to every open block (for directive extraction + highlighting ranges)
    for (const b of stack) b.rawLines.push(line);
    if (stack.length > 0 && headerBuf.trim()) {
      // trailing statement without ';' before '{' on next lines is fine; keep buffer in open block? Reset per-line top-level buffer only when no open block
    }
    if (stack.length === 0) headerBuf = '';
  });

  if (stack.length > 0) {
    for (const b of stack) errors.push(`Block '${b.header}' starting line ${b.startLine} is never closed`);
  }

  const decorate = (b: NginxBlock) => {
    if (b.type === 'server') {
      b.serverNames = extractDirective(b.rawLines, 'server_name');
      b.listens = extractDirective(b.rawLines, 'listen');
      const names = b.serverNames.length ? b.serverNames.join(' ').split(/\s+/) : ['_'];
      const listenTxt = b.listens.length
        ? b.listens.map(l => (l.match(/^\d+/) ? `:${l.match(/^\d+/)![0]}` : l)).join(' ')
        : 'no listen';
      b.label = `${names.join(' ')}  ${listenTxt}`;
    } else if (b.type === 'upstream') {
      b.label = b.arg.split(/\s+/)[0] || 'upstream';
    } else if (b.type === 'map') {
      b.label = b.arg.replace(/\s+/g, ' ').trim() || 'map';
    } else if (b.type === 'location') {
      b.label = b.arg || 'location';
    } else if (b.type === 'if') {
      b.label = b.arg || 'if';
    } else {
      b.label = b.header || b.type;
    }
    b.children.forEach(decorate);
  };
  roots.forEach(decorate);

  return { blocks: roots, lineCount: lines.length, errors };
}

/* ------------------------------------------------------------------ */
/* Syntax highlighting (lightweight, no deps)                          */
/* ------------------------------------------------------------------ */

export interface Token {
  text: string;
  cls: string;
}

const TOKEN_RE = /(#[^\n]*)|("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')|(\$[A-Za-z_][A-Za-z0-9_]*)|([A-Za-z_][A-Za-z0-9_-]*)(?=\s)|([{};])|(\b\d+[a-zA-Z%]*\b)|([^\s{};#]+)/g;

export function tokenizeNginxLine(line: string): Token[] {
  const tokens: Token[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  TOKEN_RE.lastIndex = 0;
  while ((m = TOKEN_RE.exec(line)) !== null) {
    if (m.index > last) tokens.push({ text: line.slice(last, m.index), cls: 'plain' });
    if (m[1]) tokens.push({ text: m[1], cls: 'comment' });
    else if (m[2]) tokens.push({ text: m[2], cls: 'string' });
    else if (m[3]) tokens.push({ text: m[3], cls: 'variable' });
    else if (m[4]) tokens.push({ text: m[4], cls: 'directive' });
    else if (m[5]) tokens.push({ text: m[5], cls: 'brace' });
    else if (m[6]) tokens.push({ text: m[6], cls: 'number' });
    else if (m[7]) tokens.push({ text: m[7], cls: 'plain' });
    last = m.index + m[0].length;
  }
  if (last < line.length) tokens.push({ text: line.slice(last), cls: 'plain' });
  return tokens;
}

export const TOKEN_CLASS: Record<string, string> = {
  comment: 'text-text-muted italic',
  string: 'text-status-up',
  variable: 'text-accent',
  directive: 'text-primary font-medium',
  brace: 'text-status-slow',
  number: 'text-status-slow',
  plain: 'text-text'
};
